### ISSUE TITLE
e2-micro not free?

### ISSUE THREAD

**Issue by chaoscreater** [sudo-kraken/terraform-gcp-ubuntu-container-ready-e2-micro-vm#4]
Hi there,

I can see in the Google documentation that e2-micro is free and I can see the same notes in your project readme as well. But in the pricing summary page, it shows it's not free?

![image](https://github.com/Joeharrison94/terraform-gcp-ubuntu-container-ready-e2-micro-vm/assets/18227319/d1115080-a3ba-463d-8598-58d8e638db4b)

**Comment by chaoscreater** [comment]
Never mind, I think I found my answer here:
https://stackoverflow.com/questions/69042085/does-the-e2-micro-come-under-the-gce-free-tier#:~:text=The%20machine%20type%20e2-micro,reflected%20on%20the%20billing%20reports.

**Comment by sudo-kraken** [comment]
No problem let me know if I need to alter any of the repo to better help in future.
