### ISSUE TITLE
Choosing another OS

### ISSUE THREAD

**Issue by mstoetzer** [sudo-kraken/terraform-gcp-ubuntu-container-ready-e2-micro-vm#5]
Hi there,

thanks for sharing this :)

Do you know if ubuntu is the only OS that is usable for free?
I would love to use Fedora coreOS due to it's self updating features.
I know there are some 'premium' os images but I'm not that familiar with GCP at the moment

Can share my Terraform Code if you want :)

Thanks, mstoetzer

**Comment by harrisonj94** [comment]
You can use any of these in the terraform code you would just have to adapt the ubuntu tf files to use the image you want and any changes to the scripts that run that would install ubuntu specific items i.e install commands on CentOS would be updated to use yum etc.

-     Debian: GCP offers public images for various versions of Debian. Debian is known for its stability and robustness.

-     Ubuntu: Another popular choice for cloud deployments, GCP provides images for multiple versions of Ubuntu.

-     CentOS: GCP does offer CentOS images, which are free versions of Red Hat Enterprise Linux (RHEL).

-     openSUSE: Both openSUSE Leap (stable version) and openSUSE Tumbleweed (rolling release) are available on GCP.

-     Fedora: Fedora images, sponsored by Red Hat and known for integrating the latest technologies, are also available.

-     Container-Optimized OS (COS): This is a lightweight OS built and managed by Google, optimized for running Docker containers.

-     CoreOS (Flatcar): CoreOS, which is focused on containerization, is also available, though it's essential to note that CoreOS transitioned to the Flatcar Container Linux after CoreOS's acquisition by Red Hat.

**Comment by sudo-kraken** [comment]
You can use any of these in the terraform code you would just have to adapt the ubuntu tf files to use the image you want and any changes to the scripts that run that would install ubuntu specific items i.e install commands on CentOS would be updated to use yum etc.

-     Debian: GCP offers public images for various versions of Debian. Debian is known for its stability and robustness.

-     Ubuntu: Another popular choice for cloud deployments, GCP provides images for multiple versions of Ubuntu.

-     CentOS: GCP does offer CentOS images, which are free versions of Red Hat Enterprise Linux (RHEL).

-     openSUSE: Both openSUSE Leap (stable version) and openSUSE Tumbleweed (rolling release) are available on GCP.

-     Fedora: Fedora images, sponsored by Red Hat and known for integrating the latest technologies, are also available.

-     Container-Optimized OS (COS): This is a lightweight OS built and managed by Google, optimized for running Docker containers.

-     CoreOS (Flatcar): CoreOS, which is focused on containerization, is also available, though it's essential to note that CoreOS transitioned to the Flatcar Container Linux after CoreOS's acquisition by Red Hat.
